//
//  Constant.swift
//  ChatExample
//
//  Created by Hexiao Zhang on 2020-04-03.
//  Copyright © 2020 MessageKit. All rights reserved.
//

import Foundation
extension String {
    
    struct GlobalStrings {
        
        static let zero = "0"
        static let empty = ""
        static let cancel = "Cancel"
        static let close = "Close"
        static let save = "Save"
        static let done = "Done"
        static let send = "Send"
        static let no = "No"
        static let yes = "Yes"
        static let emailAddress = "Email address"
        static let password = "Password"
        static let oldPassword = "Old Password"
        static let newPassword = "New Password"
        static let newPasswordAgain = "New Password again"
        static let organizationName = "Organization name"
        static let transitNumber = "Transit number"
        static let accountNumber = "Account number"
        static let institutionNumber = "Institution number"
        static let companyName = "Company name"
        static let companyAddress = "Company address"
        static let firstNameBank = "Holder's first Name"
        static let lastNameBank = "Holder's last Name"
        static let year = "Year of birth"
        static let month = "Month"
        static let day = "Day"
        static let email = "Email"
        static let firstAdress = "Street Address"
        static let seconAdress = "Unit/Apt (optional)"
        static let city = "City"
        static let postalCode = "Zip Code"
        static let phoneNumber = "Phone number"
        static let filterCountry = "CA"
        static let notAvailableSale = "Not available for sale"
        static let validTicket = "Valid ticket for this event"
        static let invalidTicket = "Invalid ticket \rUnknown QR Code"
        static let invalidEventTicket = "Invalid ticket \rNot this event"
        static let invalidAlreadyScanned = "Invalid ticket \rAlready scanned"
        static let ticketName = "Ticket name"
        static let unitPrice = "Unit price"
        static let description = "Description"
        static let availableTicketsNumber = "Number of available tickets"
        static let zeroEvents = "0 events"
        static let confirmation = "Confirmation"
        static let claimType = "contactUs"
//      static let zeroPrice = "0$"
        static let zeroPrice = "Free"
        static let ticketsCantBeEdited = "unEditableFields"
        static let ticketsCanBeEdited = "editableFields"
        static let ifSetLabel = "ifSetLabel"
        static let termsBtnTitle = "termsBtnTitle"
        
    }
    
    struct ScreensNames {
        
        static let logIn = "Log In"
        static let newAccount = "Create A New Account"
        static let accountSetup = "Account Setup"
        static let editMyProfile = "Edit My Profile"
        static let changePassword = "Change Password"
        static let myEvents = "My Events"
        static let eventDetails = "Event Details"
        static let tickets = "Tickets"
        static let interestedUsers = "Interested Users"
        static let userTickets = "User Tickets"
        static let scanTicket = "Scan Ticket"
        static let newTicket = "Create New Ticket"
        static let editTicket = "Edit New Ticket"
        static let category = "Category"
        static let location = "Location"
        static let selectDate = "Select Date"
        static let startDate = "Start Date"
        static let endDate = "End Date"
        static let newEvent = "Create New Event"
        static let editEvent = "Edit Event"
        static let bankAccount = "Bank Account"
        static let editBankAccount = "Edit Bank Account"
        static let contactAdmin = "Contact Admin"
        static let settings = "Settings"
        static let termsAndConditions = "Terms and conditions"
        static let privacyPolicy = "Privacy policy"
        static let contactUs = "Contact us"
        static let logOut = "Log out"
        static let band = "Band"
        static let ramble = "Ramble"
    }
    
    struct Messages {
        
        static let profileSaved = "Profile saved!"
        static let newPasswordSaved = "Password successfully changed"
        static let openCamera = "Take Photo"
        static let openLibrary = "Choose from Library"
        static let removeImage = "Remove image"
        static let errorMessage = "Something went wrong"
        static let noTicketsAvailable = "There are no tickets available. You can update the availability of each ticket or create new ones."
        static let allInterestedUsersWithTickets = "All interested users have their tickets. Well done!"
        static let allTicketsScanned = "All tickets for this user have been scanned."
        static let noTicketsForThisEvent = "You have no tickets for this events.\rCreate some!"
        static let searchAddress = "Search for an address"
        static let bankSaved = "Bank account saved!"
        static let writeSomething = "Write something here."
        static let userLocationError = "Couldn't retrieve user's location"
        static let fetchFullLocationError = "Couldn't fetch data, try later"
        static let pastDateError = "Can't select past date"
        static let selectLocation = "Please select the location"
        static let newEventSuccess = "New Event!"
        static let startNow = "Starts now"
        static let noEvents = "There are no events.\rCreate some!"
        static let noTicketsSold = "You have not sold any tickets yet. \rCome back later!"
        static let soldOut = "Sold out"
        static let noUserWithTickets = "No users have bought tickets yet."
        static let noUserNoTickets = "All interested users have their tickets. Well done!"
        static let noScannedTickets = "This user has no scanned tickets yet. \rCome back later!"
        static let contactAdmMessage = "Your request has been sent to the admin team. \rThey will contact you as soon as they can."
        static let cancelledWithInterestedUsers = "This event has been cancelled. Tickets will be refunded."
        static let cancelledWithoutInterestedUsers = "This event has been cancelled."
        static let successSendEmail = "We send an email to reset your password."
    }
    
    struct ErrorMessages {
        
        static let invalidUserPassword = "Invalid username/password"
        static let emailMandatory = "Email is mandatory"
        static let invalidEmail = "Invalid email"
        static let passwordMandatory = "Password is mandatory"
        static let invalidPassword = "Invalid Password"
        static let organizationMandatory = "Organization name is mandatory"
        static let invalidOrganization = "Invalid Organization name"
        static let customerUserError = "This email address is already used in users' APP and can’t be used for event organizer app. Try another email address."
        static let fieldMandatory = "Field is mandatory"
        static let invalidField = "Invalid field"
        static let errorFetchEvents = "Couldn't fetch events"
        static let errorFetchTickets = "Couldn't fetch tickets"
        static let errorFetchUsers = "Couldn't fetch users"
        static let errorLoadEvent = "Couldn't load event"
        static let needsCamera = "Camera access is absolutely necessary to use this app"
        static let oldPasswordWrong = "Old password is incorrect."
        static let newPasswordWrong = "New password entries don't match"
        static let phoneEmpty = "Phone can't be empty."
        static let messageEmpty = "The message can't be empty."
        static let oldPasswordEmpty = "Old password can't be empty"
        static let newPasswordEmpty = "New password can't be empty"
        static let errorTransitNumber = "Transit Number should be 5 digits"
        static let errorInstitudeNumber = "Institution Number should be 3 digits"
        static let errorAccountNumber = "Account Number should be 7-12 digits"
        static let invaliddate = "Please input a valid date"
    }
    
    struct ButtonsTitle {
        
        static let post = "Post"
        static let sold = "Sold"
        static let available = "Available"
        static let withTickets = "With tickets"
        static let noTickets = "No tickets"
        static let scanned = "Scanned"
        static let unscanned = "Unscanned"
        static let arts = "Arts"
        static let nightlife = "Nightlife"
        static let music = "Music"
        static let sports = "Sports"
        static let festivals = "Festivals"
        static let food = "Food"
        static let other = "Other"
        static let searchResult = "Search result"
        static let eventName = "Event name"
        static let manageTickets = "Manage tickets"
        static let artsLowercase = "arts"
        static let nightlifeLowercase = "nightlife"
        static let musicLowercase = "music"
        static let sportsLowercase = "sports"
        static let festivalsLowercase = "festivals"
        static let foodLowercase = "food"
        static let otherLowercase = "other"
        static let ok = "OK"
        static let deleteThisEvent = "Delete this event"
        static let deleteEvent = "Delete event"
        static let cancelEvent = "Cancel this event"
        static let fillAddress = "Fill your email address"
        static let changePasswordButton = "Change password"
        static let editMyBankAccount = "Edit my bank account"
        static let editMyProfileButton = "Edit my profile"
    }

    struct EventStatusType {
        static let cancelled = "cancelled"
        static let blocked = "blocked"
        static let reported = "reported"
        static let active = "active"
    }
    
    struct AlertMessages {
        static let areYouSureTitle = "Are you sure?"
        static let logoutMessage = "You will be disconnected from your account"
        static let openTitle = "Open with..."
        static let mapsAction = "Maps"
        static let googleMapsAction = "Google Maps"
        static let deleteMessage = "Deleting an event is permanent"
        static let cancelEventMessage = "Cancelling an event is permanent. Tickets will be refunded"
    }

}

